language: python
python:
  - "3.9"
os:
  - linux

git:
  depth: 1

env:
  - PLATFORMIO_PROJECT_DIR=examples/template-B

install:
  - pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
  - qio platform install file://.

script:
  - qio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
